
name: LR

dependencies:
- base
- containers
- mtl
- pretty
- regex-tdfa

default-extensions:
- BlockArguments
- DataKinds
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
- ViewPatterns

ghc-options: -freverse-errors -Wall -Wno-orphans

library:
  source-dirs:
  - src

executable:
  dependencies:
  - base
  - LR
  - raw-strings-qq

  source-dirs:
  - app

  main: Main.hs
