
name: lr

default-extensions:
- LambdaCase
- BlockArguments
- OverloadedRecordDot
- DefaultSignatures
- DerivingStrategies
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- NoFieldSelectors
- DuplicateRecordFields
- UndecidableInstances
- ViewPatterns
- DeriveAnyClass
- OverloadedStrings

language: GHC2021

dependencies:
- base
- containers
- monoidal-map
- mtl
- text
- hashable

ghc-options: -freverse-errors

library:
  source-dirs:
  - src